### ISSUE TITLE
Confusing output

### ISSUE THREAD

**Issue by rclanan** [hemanth/github-upstreamer#2]
Everything is working as expected but when running the command. I get this as the output: 

$ github-upstreamer
null '' ''
Upstream is set!

The null '' '' line was a bit confusing the first time I ran it, I didn't think it worked.

**Comment by hemanth** [comment]
Fixed that, thanks for reporting, I am currently working on making the test green, will do a release ASAP.

**Comment by hemanth** [comment]
Published a new version, it's fixed in that thanks.

P.S: The test is still cranky :crying_cat_face:

**Comment by rclanan** [comment]
Thanks!
