### ISSUE TITLE
Always not a fork

### ISSUE THREAD

**Issue by denysdovhan** [hemanth/github-upstreamer#4]
Don't know why, but it always return me message:

```sh
$ github-upstreamer 
Not a fork
```

Maybe I'm doing smth wrong. How can I fix this?

**Comment by hemanth** [comment]
Is you don't specific `--dir` it would by default take the current dir and your current dir is not a fork.

**Comment by denysdovhan** [comment]
![2015-11-28 17-31-47](https://cloud.githubusercontent.com/assets/3459374/11452589/fb0cf882-95f5-11e5-832f-69207842477e.png)

This is a fork for [iamstarkov/typographic-base](https://github.com/iamstarkov/typographic-base).

**Comment by hemanth** [comment]
@denysdovhan Did you run `github-upstreamer` in a loop? As the module is hitting the API without any auth, there an API request limit.

Because I see:

![screen shot 2015-11-28 at 11 10 26 pm](https://cloud.githubusercontent.com/assets/18315/11453146/6706d38a-9625-11e5-81c7-aebba9839d3d.png)

**Comment by denysdovhan** [comment]
That's because I add it manually after failed with github-package. If you try to remove upstream, it will still not work.

**Comment by hemanth** [comment]
Not able to replicate it, just cloned your fork and it works fine for me.

**Comment by denysdovhan** [comment]
Maybe is there problem with my system? I'm working on Ubuntu GNOME15.10.

**Comment by hemanth** [comment]
Shouldn't be the case, if you can tell me the exact repo steps that would help.

**Comment by denysdovhan** [comment]
Okay, what i'm doing:

* Just fork any repo, e.g [talgautb/typographic-currency](https://github.com/talgautb/typographic-currency).
* Clone [my fork](https://github.com/denysdovhan/typographic-currency) to laptop using `git clone git@github.com:denysdovhan/typographic-currency.git`.
* Navigate to this folder using `cd`.
* Run `github-upstreamer` and get `Not a fork`.
* WTF?

**Screenshot:**

![2015-11-29 13-17-59](https://cloud.githubusercontent.com/assets/3459374/11456753/a3ecddb4-969b-11e5-8e03-341cbd498dfb.png)

P.S. `pjr` it's alias for `cd ~/Projects/_Forks`

**Comment by hemanth** [comment]
Found the bug, it's not working with ssh `git@github.com:` but works fine with `URL`

![github-streamer](https://cloud.githubusercontent.com/assets/18315/11456960/9b0fa7f6-96c0-11e5-9951-0246326421fb.gif)

**Comment by denysdovhan** [comment]
Oh, that's not cool. I always use ssh. Can it be fixed?

**Comment by hemanth** [comment]
It's a pretty easy fix, currently trying to make tests green.

**Comment by hemanth** [comment]
The latest version works fine for any type of URL, please use that, thanks for reporting.

**Comment by denysdovhan** [comment]
Cool! Thank you!
You've made awesome package!

**Comment by hemanth** [comment]
:+1:
